Catch all exceptions for IOControl
On .NET Core, System.PlatformNotSupportedException is thrown instead of a SocketExcpetion. Catch all exceptions regardless of type.

System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.